class Brush{
public static void main (String args[]){
System.out.println("About the item");
System.out.println("Professional Paint Brushes: 2 Pack 10 Different Sizes ( 5/8 8 6 4 5 3 2 2 1 2/0); Length: 17.5 cm to 19.5 cm (6.9 to 7.7 inches), High Quality Wood Handle and Variety of Shapes Tip Make Mixing Color More Easier. Whether you're a beginner, hobbyist or a professional, this artist paint brushes will help you make excellent work of art. Perfect for Your Friends and Families Who Have Fun in Painting!");
System.out.println("Multi-purpose Painting Brushes: Assorted Sizes & Shapes of Paint Bush Bulk Perfect for Art Painting, Which Can Cover all Your Needs. Works Well with Art, Watercolor, Oil, Canvas, Gouache, Rocks, Enamel, Vinyl, Acrylic Painting, Body, Nail, Face Painting, Fabric, Egg, Miniature, Model, Wood, Glass, Cup, Ceramic, Fine Work, Art Class, Craft Art Painting, DIY Art Crafts etc. Acrylic Paint Brushes Allow You to do Fine Detail Painting Precisely to Reach Tight, Small Spots or Tiny Points.");
System.out.println("Artist Watercolor Paint Brushes: Smooth Wood Long Handle with UV Coating, Anti-peeling off, Non Odor and Water Resistance; Nickel ferrules Add Durable Synthetic and Anti-shedding Nylon Bristles, Individually Hand Crafted and Double-crimped with Excellent Workmanship So No Flaking Paint from Handles, Loose Bristles or Swing Ferrules with This Pro Paint Brushes Set. Intended for Long Time Use, No Compromise to the Performance or Appearance After Multiple Painting and Cleaning.");
System.out.println("Craft Paint Brushes: Clean Your Brushes Immediately After Using Them, It’s Very Convenient to Clean Them with Warm Soapy Water and Reshape the Brush Tips. Avoid Scrubbing While Cleaning. Air-dry the Detail Brushes and Store Them in the Carrying Container in a Tip-top Position for Long Time of Use. Paint Brushes Nylon Hairs Will Spring Back Perfectly After Every Brush Strokes. Never Leave Your Brushes Resting on Their Heads in Water, Solvent, or When Drying.");
System.out.println("Great Acrylic Brushes: Great idea for Artists, Beginners, Kids, Adults, Family, Friends, Girls&Boys, Teachers, Students, Great for School, Classroom, Travel, Home, Class, Office and Outdoor; Supplies for Christmas&Halloween, Birthday, Party, Back to School, New Year's Day, Valentine's Day, Easter, Mother's Day, Thanksgiving Day.");

}}