class HeadPhone{
public static void main (String args[]){
System.out.println("About this item");
System.out.println("Adopted most advanced dual 40mm dynamic sound unit and 6 EQ modes, BERIBES updated headphones wireless bluetooth black were born for audiophiles. Simply switch the headphone between balanced sound, extra powerful bass and mid treble enhancement modes. No matter you prefer rock, Jazz, Rhythm & Blues or classic music, BERIBES has always been committed to providing our customers with better sound quality as the focal point of our engineering.");
System.out.println("Low power consumption technology applied, BERIBES bluetooth headphones with built-in 500mAh battery can continually play more than 65 hours, standby more than 950 hours after one fully charge. By included 3.5mm audio cable, the wireless headphones over ear can be easily switched to wired mode when powers off. No power shortage problem anymore");
System.out.println("Made by premium materials, 0.38lb BERIBES over the ear headphones wireless bluetooth for work are the most lightweight headphones in the market. Adjustable headband makes it easy to fit all sizes heads without pains. Softer and more comfortable memory protein earmuffs protect your ear in long term using");
System.out.println("Carrying latest Bluetooth 5.3 chip, after booting, 1-3 seconds to quickly pair bluetooth. Beribes bluetooth headphones with microphone has faster and more stable transmitter range up to 33ft. Two smart devices can be connected to Beribes over-ear headphones at the same time, makes you able to pick up a call from your phone when watching movie on your pad without switching");
System.out.println("Package include a Foldable Deep Bass Headphone, 3.5mm backup audio cable, USB charging cable and User Manual. Provide a 30-day return and 12-month warranty, lifetime worry free user support, contact us anytime if you have any questions about the product, we will reply within 10 hours");
}
}